version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    environment:
      PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |  # use pipenv to install dependencies
                      sudo pip install pipenv
                      pipenv install --dev
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir ~/repo/test-reports
            pipenv run pytest -v --junitxml=~/repo/test-reports/junit.xml

